const fellowship = [
	{ name: "Frodo", species: "Hobbit", hasSword: false },
	{ name: "Aragorn", species: "Homme", hasSword: true },
	{ name: "Gandalf", species: "Maiar", hasSword: true },
	{ name: "Legolas", species: "Elfe", hasSword: true },
	{ name: "Gimli", species: "Nain", hasSword: true },
	{ name: "Boromir", species: "Homme", hasSword: true },
	{ name: "Sam", species: "Hobbit", hasSword: false },
	{ name: "Merry", species: "Hobbit", hasSword: false },
	{ name: "Pippin", species: "Hobbit", hasSword: false },
	{ name: "Gollum", species: "Hobbit", hasSword: false },
	{ name: "Sauron", species: "Maiar", hasSword: true },
	{ name: "Saruman", species: "Maiar", hasSword: true },
	{ name: "Faramir", species: "Homme", hasSword: true },
	{ name: "Eowyn", species: "Homme", hasSword: true },
	{ name: "Arwen", species: "Elfe", hasSword: false },
	{ name: "Theoden", species: "Homme", hasSword: true },
	{ name: "Elrond", species: "Elfe", hasSword: true },
];
